"""
Per-device launcher icons for a Garmin watch face project.

Garmin sets the launcher icon size per device, not per resolution: the size is
``launcherIcon`` in the SDK's ``Devices/<product>/compiler.json``. It is not a
function of ``deviceFamily`` either -- ``round-390x390`` alone spans 38x38 to
70x70 -- so the qualified ``resources-<family>/drawables/`` directories that serve
the fonts cannot express it. A per-product ``resourcePath`` entry in the jungle can.

This module renders one icon per distinct required size, writes each into its own
``resources-icon-<size>/drawables/``, and splices the per-product mapping into
``monkey.jungle`` between generated markers.

Those are defaults. A project that builds a second edition from the same tree, by
layering an edition jungle last, points the generator at that edition instead: its
own manifest, its own jungle, and an icon root such as ``premium/``. The edition's
entries come after the shared ones, so its icons override them, and an edition the
build never names never sees them. Entries are written relative to the jungle's own
directory, which is how monkeyc resolves them.

A project that documents the sizes in its README names the text introducing the
table, its anchor. Generation then rewrites the table under it, and the check reads it
back against the committed mapping, so the README cannot drift from what ships.

The artwork is supplied by the project, as a renderer: a callable taking the target
edge in pixels and returning a square image of exactly that size. Resampling one
master image is the built-in default and is right for artwork made of a few bold
shapes; it is wrong for fine strokes at a high spatial frequency, which downscaling
turns into noise long before 38x38.
"""
import importlib.util
import json
import logging
import os
import posixpath
import re
import shlex
import sys
from typing import Callable, Dict, List, Optional, Tuple

from PIL import Image

from .constants import (
    BEGIN_MARKER,
    DEFAULT_DEVICES_DIRECTORY,
    DRAWABLES_XML,
    END_MARKER,
    FALLBACK_ICON_PATH,
    ICON_DIRECTORY_TEMPLATE,
    JUNGLE_NAME,
    LAUNCHER_ICON_NAME,
    MANIFEST_NAME,
    README_NAME,
)

logger = logging.getLogger(__name__)

PRODUCT_PATTERN = re.compile(r'<iq:product\s+id="([^"]+)"')
ICON_DIRECTORY_PATTERN = re.compile(r"^resources-icon-(\d+)$")
# Any generated entry, whatever directory it points into, quoted or not: the prefix
# is group 1.
ANY_ENTRY_PATTERN = re.compile(
    r'^\S+\.resourcePath\s*=.*;"?([^;"]*?)resources-icon-\d+"?\s*$', re.MULTILINE
)
# A jungle value with a space must be quoted, or monkeyc reads a different path and
# builds without a word (SDK 9.2.0). There is no escape for these two characters.
UNWRITABLE_IN_JUNGLE = ('"', ";")
DEFAULT_COMMAND = "garmin-graphics-generator icons"
# Matched on the marker text alone, ignoring whatever attribution follows it on the
# line. A project generated by an earlier tool carries a marker naming that tool, and
# the block has to be recognised and replaced rather than appended to a second time.
BLOCK_PATTERN = re.compile(
    r"^# BEGIN generated launcher icon mapping.*?"
    r"^# END generated launcher icon mapping[^\n]*\n?",
    re.MULTILINE | re.DOTALL,
)

# One row of the README table as :func:`table` writes it. Read as width and height, so
# a row stating a non-square size disagrees with the mapping rather than going unread.
TABLE_ROW_PATTERN = re.compile(r"^\|\s*(\S+)\s*\|\s*(\d+)\s*x\s*(\d+)\s*\|\s*$")

Renderer = Callable[[int], Image.Image]


class LauncherIconError(Exception):
    """Raised when the project or the SDK cannot supply what is needed."""


def resample_renderer(master_path: str) -> Renderer:
    """
    Builds a renderer that resamples one master image to each required size.

    Right for artwork made of a few bold shapes. For fine strokes at a high spatial
    frequency, supply a renderer that draws at the target size instead.
    """
    # Copied out of the context manager rather than kept open: Image.open is lazy,
    # and the renderer outlives this call, so the handle would stay open for as long
    # as the generator runs -- and on Windows that locks the master file.
    with Image.open(master_path) as opened:
        master = opened.copy()
    if master.width != master.height:
        logger.warning(
            "master %s is %dx%d, not square; icons will be distorted",
            master_path,
            master.width,
            master.height,
        )

    def render(size: int) -> Image.Image:
        return master.resize((size, size), Image.LANCZOS)

    return render


def load_renderer(specification: str) -> Renderer:
    """
    Resolves a renderer specification to a callable.

    Accepted forms:

    ``resample:<path>``      resample that master image (see :func:`resample_renderer`)
    ``<path>.py``            a Python file exposing ``render(size)``
    ``<path>.py:<name>``     a Python file exposing ``<name>(size)``
    ``<module>:<name>``      an importable module attribute
    """
    if specification.startswith("resample:"):
        return resample_renderer(specification.split(":", 1)[1])

    target, _, attribute = specification.partition(":")
    attribute = attribute or "render"

    if target.endswith(".py"):
        if not os.path.exists(target):
            raise LauncherIconError(f"renderer file not found: {target}")
        spec = importlib.util.spec_from_file_location("_launcher_icon_renderer", target)
        if spec is None or spec.loader is None:
            raise LauncherIconError(f"cannot load renderer from {target}")
        module = importlib.util.module_from_spec(spec)
        # Imported without caching bytecode: the renderer lives in the project, and
        # a __pycache__/ beside it is an untracked build artifact the project would
        # have to ignore. Restored after, as the flag is process-wide.
        writes_bytecode = sys.dont_write_bytecode
        sys.dont_write_bytecode = True
        try:
            spec.loader.exec_module(module)
        finally:
            sys.dont_write_bytecode = writes_bytecode
    else:
        module = importlib.import_module(target)

    renderer = getattr(module, attribute, None)
    if not callable(renderer):
        raise LauncherIconError(
            f"renderer {specification}: {target} has no callable {attribute!r}"
        )
    return renderer


def read_png_size(path: str) -> Optional[Tuple[int, int]]:
    """Reads (width, height) out of a PNG header, without decoding the image."""
    with open(path, "rb") as handle:
        head = handle.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n" or head[12:16] != b"IHDR":
        return None
    return (
        int.from_bytes(head[16:20], "big"),
        int.from_bytes(head[20:24], "big"),
    )


class LauncherIconGenerator:
    """
    A fluent API class to render per-device launcher icons and map products to them.
    """

    def __init__(self):
        self._project_directory: str = "."
        self._devices_directory: str = os.path.expanduser(DEFAULT_DEVICES_DIRECTORY)
        self._renderer: Optional[Renderer] = None
        self._fallback_icon: bool = True
        self._manifest: str = MANIFEST_NAME
        self._jungle: str = JUNGLE_NAME
        self._icon_root: str = ""
        self._fallback_path: str = FALLBACK_ICON_PATH
        self._readme: str = README_NAME
        self._readme_anchor: Optional[str] = None
        self._sizes: Dict[str, int] = {}

    # ------------------------------------------------------------------ setters

    def set_project_directory(self, path: str) -> "LauncherIconGenerator":
        """Sets the watch face project directory, which the other paths are under."""
        self._project_directory = path
        return self

    def set_devices_directory(self, path: str) -> "LauncherIconGenerator":
        """Sets the SDK directory holding one compiler.json per device."""
        self._devices_directory = os.path.expanduser(path)
        return self

    def set_renderer(self, renderer: Renderer) -> "LauncherIconGenerator":
        """Sets the callable that draws one icon at a given edge in pixels."""
        self._renderer = renderer
        return self

    def set_fallback_icon(self, enabled: bool) -> "LauncherIconGenerator":
        """
        Sets whether to also write the fallback icon (see :meth:`set_fallback_path`).

        That copy is drawn at the largest required size and applies to a product
        added to the manifest before the icons are regenerated.
        """
        self._fallback_icon = enabled
        return self

    def set_manifest(self, path: str) -> "LauncherIconGenerator":
        """Sets the manifest the products are read from, relative to the project."""
        self._manifest = path
        return self

    def set_jungle(self, path: str) -> "LauncherIconGenerator":
        """Sets the jungle the mapping is spliced into, relative to the project."""
        self._jungle = path
        return self

    def set_icon_root(self, path: str) -> "LauncherIconGenerator":
        """
        Sets the directory the resources-icon-<size>/ directories live in.

        Relative to the project, and empty for the project itself. The jungle entries
        carry its path relative to the jungle's own directory, since that is what
        monkeyc resolves them against.
        """
        self._icon_root = path
        return self

    def set_fallback_path(self, path: str) -> "LauncherIconGenerator":
        """
        Sets where the fallback icon is written, relative to the project.

        Only the image is written. The drawables.xml declaring it belongs to the
        project, because it may declare other bitmaps too.
        """
        self._fallback_path = path
        return self

    def set_readme_anchor(
        self, anchor: Optional[str], readme: str = README_NAME
    ) -> "LauncherIconGenerator":
        """
        Sets the text the size table follows in ``readme``, or None for no table.

        Typically the sentence introducing the table. The table is the run of ``|``
        lines after it and before the next heading; generation rewrites it, or inserts
        one after the anchor's line, and the check compares it with the mapping.
        Without an anchor the README is neither written nor checked. ``readme`` is
        relative to the project.
        """
        self._readme_anchor = anchor or None
        self._readme = readme
        return self

    # ------------------------------------------------------------------- paths

    def _path(self, *parts: str) -> str:
        return os.path.join(self._project_directory, *parts)

    def _icon_directory(self, size: int) -> str:
        return self._path(
            self._icon_root, ICON_DIRECTORY_TEMPLATE.format(size=size), "drawables"
        )

    def _relative(self, path: str, start: str) -> str:
        """``path`` relative to ``start``, both under the project, in jungle form."""
        try:
            relative = os.path.relpath(self._path(path), self._path(start))
        except ValueError as error:  # different drives, on Windows
            raise LauncherIconError(f"{path} is not reachable from {start}") from error
        return normalise_directory(relative)

    def _entry_prefix(self) -> str:
        """The icon root as the jungle's entries name it: relative to the jungle."""
        return self._relative(self._icon_root, os.path.dirname(self._jungle))

    def _root_label(self) -> str:
        """The icon root relative to the project, for messages and orphan names."""
        return self._relative(self._icon_root, "")

    def _command(self) -> str:
        """
        The command line that regenerates this mapping, for the jungle's comment.

        An edition's carries everything the CLI requires of one -- the jungle, the
        icon root, and an explicit fallback choice -- so it can be pasted and rerun.
        The shared edition's names only what differs from the defaults.
        """
        jungle = self._relative(self._jungle, "")
        root = self._root_label()
        edition = jungle != JUNGLE_NAME or root != ""
        fallback = self._relative(self._fallback_path, "")

        options = []
        if self._relative(self._manifest, "") != MANIFEST_NAME:
            options += ["--manifest", self._relative(self._manifest, "")]
        if edition:
            options += ["--jungle", jungle, "--icon-root", root or "."]
        if not self._fallback_icon:
            options.append("--no-fallback-icon")
        elif edition or fallback != FALLBACK_ICON_PATH:
            options += ["--fallback-icon", fallback]
        if self._readme_anchor is not None:
            if self._relative(self._readme, "") != README_NAME:
                options += ["--readme", self._relative(self._readme, "")]
            options += ["--readme-anchor", self._readme_anchor]
        return " ".join([DEFAULT_COMMAND] + [shlex.quote(o) for o in options])

    def _output_directories(self) -> List[str]:
        """Every directory generation writes into, for the preflight."""
        directories = [
            self._icon_directory(size) for size in sorted(set(self._sizes.values()))
        ]
        if self._fallback_icon:
            directories.append(os.path.dirname(self._path(self._fallback_path)))
        return directories

    # ------------------------------------------------------------------ sources

    def products(self) -> List[str]:
        """Reads the product ids declared in the project's manifest."""
        manifest = self._path(self._manifest)
        if not os.path.exists(manifest):
            raise LauncherIconError(f"no manifest at {manifest}")
        with open(manifest, "r", encoding="utf-8") as handle:
            return PRODUCT_PATTERN.findall(handle.read())

    def resolve_sizes(self) -> "LauncherIconGenerator":
        """Looks up the required icon size of every product in the SDK definitions."""
        if not os.path.isdir(self._devices_directory):
            raise LauncherIconError(
                f"no device definitions at {self._devices_directory}; "
                "install the SDK, or pass --devices-directory"
            )
        sizes: Dict[str, int] = {}
        missing: List[str] = []
        for product in self.products():
            definition = os.path.join(self._devices_directory, product, "compiler.json")
            if not os.path.exists(definition):
                missing.append(product)
                continue
            with open(definition, "r", encoding="utf-8") as handle:
                icon = json.load(handle)["launcherIcon"]
            if icon["width"] != icon["height"]:
                raise LauncherIconError(
                    f"{product}: launcher icon {icon['width']}x{icon['height']} "
                    "is not square"
                )
            sizes[product] = icon["width"]
        if missing:
            raise LauncherIconError(
                "no device definition for "
                + ", ".join(missing[:5])
                + (f" (and {len(missing) - 5} more)" if len(missing) > 5 else "")
                + f"; looked under {self._devices_directory}"
            )
        self._sizes = sizes
        logger.info(
            "%d products need %d distinct icon sizes: %s",
            len(sizes),
            len(set(sizes.values())),
            ", ".join(str(s) for s in sorted(set(sizes.values()), reverse=True)),
        )
        return self

    @property
    def sizes(self) -> Dict[str, int]:
        """The resolved product to icon size mapping."""
        return dict(self._sizes)

    # ---------------------------------------------------------------- validation

    def validate(self) -> "LauncherIconGenerator":
        """
        Checks the paths before anything is written, so a mistake costs nothing.

        Raises when the manifest or the jungle is missing, when the fallback path is
        not a PNG file, when the icon root cannot be written into a jungle, and when
        the jungle's generated block maps anything into a different directory:
        writing would replace another edition's mapping.
        """
        self.products()
        jungle = self._path(self._jungle)
        if not os.path.isfile(jungle):
            hint = (
                "; --jungle takes the one file to write into, not a build list"
                if ";" in self._jungle
                else ""
            )
            raise LauncherIconError(f"no jungle at {jungle}{hint}")
        with open(jungle, "r", encoding="utf-8") as handle:
            block = BLOCK_PATTERN.search(handle.read())
        if block is not None:
            found = {
                normalise_directory(prefix)
                for prefix in ANY_ENTRY_PATTERN.findall(block.group(0))
            }
            expected = self._entry_prefix()
            # Exactly, not "includes": a block mixing roots would lose the foreign
            # entries to the splice just as surely as an all-foreign one.
            if found and found != {expected}:
                raise LauncherIconError(
                    f"the generated block in {self._jungle} maps icons into "
                    f"{', '.join(repr(f or '.') for f in sorted(found))}, "
                    f"not only {expected or '.'!r}, and writing would replace it. Check "
                    "--jungle and --icon-root; to move the icons, delete the block first"
                )
        unwritable = [c for c in UNWRITABLE_IN_JUNGLE if c in self._entry_prefix()]
        if unwritable:
            raise LauncherIconError(
                f"the icon root {self._icon_root!r} contains {unwritable[0]!r}, which a "
                "jungle entry cannot hold"
            )
        if self._fallback_icon:
            fallback = self._path(self._fallback_path)
            if os.path.isdir(fallback) or not fallback.lower().endswith(".png"):
                raise LauncherIconError(
                    f"the fallback icon path {self._fallback_path!r} is not a .png file"
                )
        if self._readme_anchor is not None:
            self._read_readme()
        return self

    # ---------------------------------------------------------------- generation

    def _write_icon(self, path: str, size: int) -> None:
        if self._renderer is None:
            raise LauncherIconError("no renderer set")
        image = self._renderer(size)
        if image.size != (size, size):
            raise LauncherIconError(
                f"renderer returned {image.width}x{image.height} for size {size}"
            )
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            image.save(path)
        except OSError as error:
            raise LauncherIconError(f"cannot write {path}: {error}") from error

    def generate_icons(self) -> "LauncherIconGenerator":
        """Renders one icon per distinct required size, each into its own directory."""
        self.validate()
        if not self._sizes:
            self.resolve_sizes()

        # Before rendering anything: a file standing where a directory has to go
        # would otherwise stop generation halfway, with some icons written.
        for directory in self._output_directories():
            blocked = blocking_file(directory)
            if blocked:
                raise LauncherIconError(
                    f"cannot create {directory}: {blocked} is a file, not a directory"
                )

        for size in sorted(set(self._sizes.values()), reverse=True):
            directory = self._icon_directory(size)
            self._write_icon(os.path.join(directory, LAUNCHER_ICON_NAME), size)
            with open(
                os.path.join(directory, "drawables.xml"), "w", encoding="utf-8"
            ) as handle:
                handle.write(DRAWABLES_XML)
            logger.info("wrote %s at %dx%d", directory, size, size)

        if self._fallback_icon:
            largest = max(self._sizes.values())
            self._write_icon(self._path(self._fallback_path), largest)
            logger.info("wrote the %dx%d fallback icon", largest, largest)

        for directory in self.unmapped_directories(set(self._sizes.values())):
            logger.warning("%s is required by no product; remove it", directory)

        return self

    # ------------------------------------------------------------------- jungle

    def write_mapping(self) -> "LauncherIconGenerator":
        """Splices the per-product resourcePath mapping into the project's jungle."""
        self.validate()
        if not self._sizes:
            self.resolve_sizes()

        jungle = self._path(self._jungle)
        with open(jungle, "r", encoding="utf-8") as handle:
            text = handle.read()

        block = mapping_block(self._sizes, self._entry_prefix(), self._command())
        with open(jungle, "w", encoding="utf-8") as handle:
            handle.write(splice(text, block))
        logger.info("mapped %d products in %s", len(self._sizes), self._jungle)
        return self

    # ------------------------------------------------------------------- README

    def _read_readme(self) -> str:
        """The README's text, which has to hold the anchor."""
        readme = self._path(self._readme)
        if not os.path.isfile(readme):
            raise LauncherIconError(f"no README at {readme}")
        with open(readme, "r", encoding="utf-8") as handle:
            text = handle.read()
        if self._readme_anchor not in text:
            raise LauncherIconError(
                f"{self._readme} has no {self._readme_anchor!r} to put the icon table "
                "under; check --readme-anchor"
            )
        return text

    def write_readme(self) -> "LauncherIconGenerator":
        """
        Rewrites the README's size table under the anchor, or inserts one there.

        Does nothing when no anchor is set, so a project without a README table is
        unaffected.
        """
        if self._readme_anchor is None:
            return self
        self.validate()
        if not self._sizes:
            self.resolve_sizes()
        text = self._read_readme()
        with open(self._path(self._readme), "w", encoding="utf-8") as handle:
            handle.write(splice_table(text, self._readme_anchor, table(self._sizes)))
        logger.info("tabulated %d products in %s", len(self._sizes), self._readme)
        return self

    def _readme_table(self) -> Optional[Dict[str, Tuple[int, int]]]:
        """
        Reads the size table back out of the README, as product to (width, height).

        None when no anchor is set; raises when the README or the anchor is missing.
        """
        if self._readme_anchor is None:
            return None
        return read_table(self._read_readme(), self._readme_anchor)

    def mapping(self) -> Dict[str, int]:
        """
        Reads the committed mapping back out of the jungle.

        Only entries naming this generator's icon root count: an entry pointing into
        another root is not a mapping to these icons, and reads as a product with no
        mapping at all.
        """
        jungle = self._path(self._jungle)
        if not os.path.exists(jungle):
            return {}
        with open(jungle, "r", encoding="utf-8") as handle:
            text = handle.read()
        block = BLOCK_PATTERN.search(text)
        if block is None:
            return {}
        return {
            match.group(1): int(match.group(2))
            for match in mapping_pattern(self._entry_prefix()).finditer(block.group(0))
        }

    def unmapped_directories(self, sizes) -> List[str]:
        """Icon directories present under the icon root that no product asks for."""
        root = self._path(self._icon_root)
        if not os.path.isdir(root):
            return []
        found = (
            (name, ICON_DIRECTORY_PATTERN.match(name)) for name in os.listdir(root)
        )
        return sorted(
            posixpath.join(self._root_label(), name)
            for name, match in found
            if match and int(match.group(1)) not in sizes
        )

    # -------------------------------------------------------------------- output

    def table(self) -> str:
        """
        The product to icon size table, as markdown, for a project README.

        Reads the committed mapping, and falls back to the SDK when there is none --
        the table is most wanted when writing the README for the first time, which is
        before anything has been generated.
        """
        jungle = self._path(self._jungle)
        if not os.path.isfile(jungle):
            # Falling back to the SDK here would tabulate a jungle that is not there.
            raise LauncherIconError(f"no jungle at {jungle}")
        sizes = self.mapping() or self._sizes
        if not sizes:
            sizes = self.resolve_sizes().sizes
        if not sizes:
            raise LauncherIconError(
                f"no products to tabulate: {self._path(self._manifest)} declares none"
            )
        return table(sizes)

    def check(self) -> List[Tuple[bool, str]]:
        """
        Verifies the committed icons and mapping, as a list of (passed, message).

        Needs no SDK: the mapping in the jungle is itself the device to size table,
        and is cross-checked against the SDK only when the definitions are present.
        """
        report: List[Tuple[bool, str]] = []
        jungle = self._path(self._jungle)
        if not os.path.isfile(jungle):
            # Not an empty mapping: every product would read as unmapped and every
            # icon directory as an orphan, and none of it would name the cause.
            return [(False, f"no jungle at {jungle}")]
        mapped = self.mapping()
        products = set(self.products())

        missing = sorted(products - set(mapped))
        extra = sorted(set(mapped) - products)
        report.append(
            (
                not missing,
                f"every manifest product has an icon resourcePath ({len(products)})"
                if not missing
                else f"no icon resourcePath for {missing}",
            )
        )
        report.append(
            (
                not extra,
                "no resourcePath for a product outside the manifest"
                if not extra
                else f"resourcePath for unknown products {extra}",
            )
        )

        for size in sorted(set(mapped.values()), reverse=True):
            icon = os.path.join(self._icon_directory(size), LAUNCHER_ICON_NAME)
            if not os.path.exists(icon):
                report.append((False, f"{icon} is missing"))
                continue
            actual = read_png_size(icon)
            report.append(
                (
                    actual == (size, size),
                    f"{icon} is {size}x{size}"
                    if actual == (size, size)
                    else f"{icon} is {actual}, its directory promises {size}x{size}",
                )
            )
            declaration = os.path.join(self._icon_directory(size), "drawables.xml")
            declared = os.path.exists(declaration)
            if declared:
                with open(declaration, "r", encoding="utf-8") as handle:
                    # Compared whole rather than searched for "LauncherIcon": the file
                    # is generated, and a declaration naming the wrong filename
                    # contains that substring too and would pass, only to fail at
                    # compile time.
                    declared = handle.read() == DRAWABLES_XML
            report.append(
                (
                    declared,
                    f"{declaration} declares LauncherIcon -> {LAUNCHER_ICON_NAME}",
                )
            )

        report.extend(self._check_fallback(mapped))

        orphans = self.unmapped_directories(set(mapped.values()))
        report.append(
            (
                not orphans,
                "no icon directory left unmapped"
                if not orphans
                else f"icon directories no product asks for: {orphans}",
            )
        )

        report.extend(self._check_readme(mapped))
        report.extend(self._check_against_sdk(mapped))
        return report

    def _check_fallback(self, mapped: Dict[str, int]) -> List[Tuple[bool, str]]:
        """
        The fallback is the largest size mapped: read from the mapping, not the SDK.

        Not checked when it is not written, nor without a mapping to size it from;
        the missing mapping is reported already.
        """
        if not self._fallback_icon or not mapped:
            return []
        fallback = self._path(self._fallback_path)
        largest = max(mapped.values())
        if not os.path.isfile(fallback):
            return [(False, f"{fallback} is missing")]
        actual = read_png_size(fallback)
        return [
            (
                actual == (largest, largest),
                f"{fallback} is the {largest}x{largest} fallback, the largest size mapped"
                if actual == (largest, largest)
                else f"{fallback} is "
                + (f"{actual[0]}x{actual[1]}" if actual else "not a PNG")
                + f", the largest size mapped is {largest}x{largest}",
            )
        ]

    def _check_readme(self, mapped: Dict[str, int]) -> List[Tuple[bool, str]]:
        """The README's table states the mapping, product by product."""
        try:
            stated = self._readme_table()
        except LauncherIconError as error:
            return [(False, str(error))]
        if stated is None:
            return []
        if not stated:
            return [
                (
                    False,
                    f"{self._readme} has no icon table under {self._readme_anchor!r}",
                )
            ]
        wrong = []
        for product in sorted(set(stated) | set(mapped)):
            row = stated.get(product)
            size = mapped.get(product)
            if row is not None and size is not None and row == (size, size):
                continue
            wrong.append(
                f"{product} ("
                + ("not in the table" if row is None else f"table {row[0]} x {row[1]}")
                + ", "
                + ("not mapped" if size is None else f"mapping {size} x {size}")
                + ")"
            )
        return [
            (
                not wrong,
                f"{self._readme}'s icon table agrees with the mapping ({len(stated)})"
                if not wrong
                else f"{self._readme}'s icon table disagrees with the mapping on "
                + ", ".join(wrong),
            )
        ]

    def _check_against_sdk(self, mapped: Dict[str, int]) -> List[Tuple[bool, str]]:
        try:
            self.resolve_sizes()
        except LauncherIconError as error:
            logger.info("not cross-checked against the SDK: %s", error)
            return []
        wrong = sorted(
            (product, mapped[product], size)
            for product, size in self._sizes.items()
            if product in mapped and mapped[product] != size
        )
        return [
            (
                not wrong,
                f"every mapping matches the device's launcherIcon ({len(self._sizes)})"
                if not wrong
                else f"mappings disagreeing with the SDK: {wrong[:3]}",
            )
        ]


# ------------------------------------------------------------------- free helpers


def normalise_directory(path: str) -> str:
    """A directory in the form a jungle entry names it: '/'-separated, '' for '.'."""
    path = posixpath.normpath(path.replace(os.sep, "/"))
    return "" if path == "." else path


def blocking_file(directory: str) -> Optional[str]:
    """The nearest existing ancestor of ``directory`` when it is not a directory."""
    path = os.path.abspath(directory)
    while not os.path.exists(path):
        parent = os.path.dirname(path)
        if parent == path:
            return None
        path = parent
    return None if os.path.isdir(path) else path


def needs_quotes(value: str) -> bool:
    """Whether a jungle value has to be quoted: it does when it holds whitespace."""
    return any(c.isspace() for c in value)


def mapping_pattern(icon_root: str = "") -> "re.Pattern[str]":
    """
    Matches one generated jungle entry pointing into ``icon_root``.

    Exactly as :func:`mapping_block` writes it: quoted when the path holds a space,
    and not otherwise. An unquoted path with a space is not this mapping, since
    monkeyc does not read it as one.
    """
    icon_root = normalise_directory(icon_root)
    prefix = re.escape(icon_root + "/") if icon_root else ""
    quote = '"' if needs_quotes(icon_root) else ""
    return re.compile(
        rf"^(\S+)\.resourcePath\s*=.*;{quote}{prefix}resources-icon-(\d+){quote}\s*$",
        re.MULTILINE,
    )


def mapping_block(
    sizes: Dict[str, int], icon_root: str = "", command: str = DEFAULT_COMMAND
) -> str:
    """
    Renders the generated jungle block for a product to size mapping.

    ``icon_root`` is relative to the jungle's directory, as monkeyc resolves it.
    """
    icon_root = normalise_directory(icon_root)
    lines = [
        BEGIN_MARKER,
        "# Launcher icon size is per device, not per device family.",
        f"# Regenerate with: {command}",
    ]
    for product in sorted(sizes):
        directory = posixpath.join(
            icon_root, ICON_DIRECTORY_TEMPLATE.format(size=sizes[product])
        )
        if needs_quotes(directory):
            directory = f'"{directory}"'
        lines.append(f"{product}.resourcePath = $({product}.resourcePath);{directory}")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def splice(text: str, block: str) -> str:
    """
    Replaces the generated block in a jungle file, or appends it if absent.

    Every existing block goes, not just the first: a project generated by an earlier
    tool carries a marker naming that tool, and leaving it in place would map each
    product twice.
    """
    first = BLOCK_PATTERN.search(text)
    if first is None:
        return text.rstrip("\n") + "\n\n" + block
    return text[: first.start()] + block + BLOCK_PATTERN.sub("", text[first.end() :])


def table(sizes: Dict[str, int]) -> str:
    """
    Renders the product to icon size table as markdown.

    Sorted by size rather than by product, because the point the table has to make
    is that the sizes cut across every other way of grouping the devices.
    """
    rows = [
        (product, f"{sizes[product]} x {sizes[product]}")
        for product in sorted(sizes, key=lambda p: (-sizes[p], p))
    ]
    left = max([len("Product")] + [len(row[0]) for row in rows])
    right = max([len("Icon")] + [len(row[1]) for row in rows])
    lines = [
        f'| {"Product":<{left}} | {"Icon":>{right}} |',
        f'| :{"-" * (left - 1)} | {"-" * (right - 1)}: |',
    ]
    lines += [f"| {product:<{left}} | {size:>{right}} |" for product, size in rows]
    return "\n".join(lines) + "\n"


def _table_span(lines: List[str]) -> Tuple[int, int]:
    """
    Where the table is in the lines following the anchor: (start, end), or the
    point to insert one at, twice, when there is none.

    The first run of ``|`` lines, looked for only up to the next markdown heading, so
    that a table in a later section is never mistaken for this one. ``lines[0]`` is
    the rest of the anchor's own line, and is never the table.
    """
    for index in range(1, len(lines)):
        line = lines[index]
        if line.startswith("#"):
            break
        if line.startswith("|"):
            end = index
            while end < len(lines) and lines[end].startswith("|"):
                end += 1
            return index, end
    return 1, 1


def splice_table(text: str, anchor: str, rendered: str) -> str:
    """
    Replaces the table under ``anchor`` in a markdown text, or inserts one.

    An inserted table goes right after the anchor's line, set off by a blank line on
    either side. Everything else in the text is left as it was.
    """
    head, tail = text.split(anchor, 1)
    lines = tail.split("\n")
    rows = rendered.rstrip("\n").split("\n")
    start, end = _table_span(lines)
    if start == end:
        # No table yet. Blank lines after the anchor fold into the one that sets the
        # table off, so the text reads the same whatever spacing it had.
        while end < len(lines) and not lines[end].strip():
            end += 1
        rows = [""] + rows + [""]
    return head + anchor + "\n".join(lines[:start] + rows + lines[end:])


def read_table(text: str, anchor: str) -> Dict[str, Tuple[int, int]]:
    """
    Reads the table under ``anchor`` back, as product to (width, height).

    Empty when there is no table there, or the anchor is not in the text.
    """
    if anchor not in text:
        return {}
    lines = text.split(anchor, 1)[1].split("\n")
    start, end = _table_span(lines)
    stated: Dict[str, Tuple[int, int]] = {}
    for line in lines[start:end]:
        match = TABLE_ROW_PATTERN.match(line)
        if match:
            stated[match.group(1)] = (int(match.group(2)), int(match.group(3)))
    return stated


__all__ = [
    "LauncherIconError",
    "LauncherIconGenerator",
    "load_renderer",
    "mapping_block",
    "mapping_pattern",
    "needs_quotes",
    "normalise_directory",
    "read_png_size",
    "read_table",
    "resample_renderer",
    "splice",
    "splice_table",
    "table",
]
