"""
Per-device launcher icons for a Garmin watch face project.

Garmin sets the launcher icon size per device, not per resolution: the size is
``launcherIcon`` in the SDK's ``Devices/<product>/compiler.json``. It is not a
function of ``deviceFamily`` either -- ``round-390x390`` alone spans 38x38 to
70x70 -- so the qualified ``resources-<family>/drawables/`` directories that serve
the fonts cannot express it. A per-product ``resourcePath`` entry in the jungle can.

This module renders one icon per distinct required size, writes each into its own
``resources-icon-<size>/drawables/``, and splices the per-product mapping into
``monkey.jungle`` between generated markers.

The artwork is supplied by the project, as a renderer: a callable taking the target
edge in pixels and returning a square image of exactly that size. Resampling one
master image is the built-in default and is right for artwork made of a few bold
shapes; it is wrong for fine strokes at a high spatial frequency, which downscaling
turns into noise long before 38x38.
"""
import importlib.util
import json
import logging
import os
import re
from typing import Callable, Dict, List, Optional, Tuple

from PIL import Image

from .constants import (
    BEGIN_MARKER,
    DEFAULT_DEVICES_DIRECTORY,
    DRAWABLES_XML,
    END_MARKER,
    ICON_DIRECTORY_TEMPLATE,
    JUNGLE_NAME,
    LAUNCHER_ICON_NAME,
    MANIFEST_NAME,
)

logger = logging.getLogger(__name__)

PRODUCT_PATTERN = re.compile(r'<iq:product\s+id="([^"]+)"')
ICON_DIRECTORY_PATTERN = re.compile(r"^resources-icon-(\d+)$")
MAPPING_PATTERN = re.compile(
    r"^(\S+)\.resourcePath\s*=.*;resources-icon-(\d+)\s*$", re.MULTILINE
)
# Matched on the marker text alone, ignoring whatever attribution follows it on the
# line. A project generated by an earlier tool carries a marker naming that tool, and
# the block has to be recognised and replaced rather than appended to a second time.
BLOCK_PATTERN = re.compile(
    r"^# BEGIN generated launcher icon mapping.*?"
    r"^# END generated launcher icon mapping[^\n]*\n?",
    re.MULTILINE | re.DOTALL,
)

Renderer = Callable[[int], Image.Image]


class LauncherIconError(Exception):
    """Raised when the project or the SDK cannot supply what is needed."""


def resample_renderer(master_path: str) -> Renderer:
    """
    Builds a renderer that resamples one master image to each required size.

    Right for artwork made of a few bold shapes. For fine strokes at a high spatial
    frequency, supply a renderer that draws at the target size instead.
    """
    master = Image.open(master_path)
    if master.width != master.height:
        logger.warning(
            "master %s is %dx%d, not square; icons will be distorted",
            master_path,
            master.width,
            master.height,
        )

    def render(size: int) -> Image.Image:
        return master.resize((size, size), Image.LANCZOS)

    return render


def load_renderer(specification: str) -> Renderer:
    """
    Resolves a renderer specification to a callable.

    Accepted forms:

    ``resample:<path>``      resample that master image (see :func:`resample_renderer`)
    ``<path>.py``            a Python file exposing ``render(size)``
    ``<path>.py:<name>``     a Python file exposing ``<name>(size)``
    ``<module>:<name>``      an importable module attribute
    """
    if specification.startswith("resample:"):
        return resample_renderer(specification.split(":", 1)[1])

    target, _, attribute = specification.partition(":")
    attribute = attribute or "render"

    if target.endswith(".py"):
        if not os.path.exists(target):
            raise LauncherIconError(f"renderer file not found: {target}")
        spec = importlib.util.spec_from_file_location("_launcher_icon_renderer", target)
        if spec is None or spec.loader is None:
            raise LauncherIconError(f"cannot load renderer from {target}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    else:
        module = importlib.import_module(target)

    renderer = getattr(module, attribute, None)
    if not callable(renderer):
        raise LauncherIconError(
            f"renderer {specification}: {target} has no callable {attribute!r}"
        )
    return renderer


def read_png_size(path: str) -> Optional[Tuple[int, int]]:
    """Reads (width, height) out of a PNG header, without decoding the image."""
    with open(path, "rb") as handle:
        head = handle.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n" or head[12:16] != b"IHDR":
        return None
    return (
        int.from_bytes(head[16:20], "big"),
        int.from_bytes(head[20:24], "big"),
    )


class LauncherIconGenerator:
    """
    A fluent API class to render per-device launcher icons and map products to them.
    """

    def __init__(self):
        self._project_directory: str = "."
        self._devices_directory: str = os.path.expanduser(DEFAULT_DEVICES_DIRECTORY)
        self._renderer: Optional[Renderer] = None
        self._fallback_icon: bool = True
        self._sizes: Dict[str, int] = {}

    # ------------------------------------------------------------------ setters

    def set_project_directory(self, path: str) -> "LauncherIconGenerator":
        """Sets the watch face project directory, the one holding manifest.xml."""
        self._project_directory = path
        return self

    def set_devices_directory(self, path: str) -> "LauncherIconGenerator":
        """Sets the SDK directory holding one compiler.json per device."""
        self._devices_directory = os.path.expanduser(path)
        return self

    def set_renderer(self, renderer: Renderer) -> "LauncherIconGenerator":
        """Sets the callable that draws one icon at a given edge in pixels."""
        self._renderer = renderer
        return self

    def set_fallback_icon(self, enabled: bool) -> "LauncherIconGenerator":
        """
        Sets whether to also write resources/drawables/launcher_icon.png.

        That copy is drawn at the largest required size and applies to a product
        added to the manifest before the icons are regenerated.
        """
        self._fallback_icon = enabled
        return self

    # ------------------------------------------------------------------- paths

    def _path(self, *parts: str) -> str:
        return os.path.join(self._project_directory, *parts)

    def _icon_directory(self, size: int) -> str:
        return self._path(ICON_DIRECTORY_TEMPLATE.format(size=size), "drawables")

    # ------------------------------------------------------------------ sources

    def products(self) -> List[str]:
        """Reads the product ids declared in the project's manifest."""
        manifest = self._path(MANIFEST_NAME)
        if not os.path.exists(manifest):
            raise LauncherIconError(f"no {MANIFEST_NAME} in {self._project_directory}")
        with open(manifest, "r", encoding="utf-8") as handle:
            return PRODUCT_PATTERN.findall(handle.read())

    def resolve_sizes(self) -> "LauncherIconGenerator":
        """Looks up the required icon size of every product in the SDK definitions."""
        if not os.path.isdir(self._devices_directory):
            raise LauncherIconError(
                f"no device definitions at {self._devices_directory}; "
                "install the SDK, or pass --devices-directory"
            )
        sizes: Dict[str, int] = {}
        missing: List[str] = []
        for product in self.products():
            definition = os.path.join(self._devices_directory, product, "compiler.json")
            if not os.path.exists(definition):
                missing.append(product)
                continue
            with open(definition, "r", encoding="utf-8") as handle:
                icon = json.load(handle)["launcherIcon"]
            if icon["width"] != icon["height"]:
                raise LauncherIconError(
                    f"{product}: launcher icon {icon['width']}x{icon['height']} "
                    "is not square"
                )
            sizes[product] = icon["width"]
        if missing:
            raise LauncherIconError(
                "no device definition for "
                + ", ".join(missing[:5])
                + (f" (and {len(missing) - 5} more)" if len(missing) > 5 else "")
                + f"; looked under {self._devices_directory}"
            )
        self._sizes = sizes
        logger.info(
            "%d products need %d distinct icon sizes: %s",
            len(sizes),
            len(set(sizes.values())),
            ", ".join(str(s) for s in sorted(set(sizes.values()), reverse=True)),
        )
        return self

    @property
    def sizes(self) -> Dict[str, int]:
        """The resolved product to icon size mapping."""
        return dict(self._sizes)

    # ---------------------------------------------------------------- generation

    def _write_icon(self, path: str, size: int) -> None:
        if self._renderer is None:
            raise LauncherIconError("no renderer set")
        image = self._renderer(size)
        if image.size != (size, size):
            raise LauncherIconError(
                f"renderer returned {image.width}x{image.height} for size {size}"
            )
        os.makedirs(os.path.dirname(path), exist_ok=True)
        image.save(path)

    def generate_icons(self) -> "LauncherIconGenerator":
        """Renders one icon per distinct required size, each into its own directory."""
        if not self._sizes:
            self.resolve_sizes()

        for size in sorted(set(self._sizes.values()), reverse=True):
            directory = self._icon_directory(size)
            self._write_icon(os.path.join(directory, LAUNCHER_ICON_NAME), size)
            with open(
                os.path.join(directory, "drawables.xml"), "w", encoding="utf-8"
            ) as handle:
                handle.write(DRAWABLES_XML)
            logger.info("wrote %s at %dx%d", directory, size, size)

        if self._fallback_icon:
            largest = max(self._sizes.values())
            self._write_icon(
                self._path("resources", "drawables", LAUNCHER_ICON_NAME), largest
            )
            logger.info("wrote the %dx%d fallback icon", largest, largest)

        for directory in self.unmapped_directories(set(self._sizes.values())):
            logger.warning("%s is required by no product; remove it", directory)

        return self

    # ------------------------------------------------------------------- jungle

    def write_mapping(self) -> "LauncherIconGenerator":
        """Splices the per-product resourcePath mapping into the project's jungle."""
        if not self._sizes:
            self.resolve_sizes()

        jungle = self._path(JUNGLE_NAME)
        if not os.path.exists(jungle):
            raise LauncherIconError(f"no {JUNGLE_NAME} in {self._project_directory}")
        with open(jungle, "r", encoding="utf-8") as handle:
            text = handle.read()

        with open(jungle, "w", encoding="utf-8") as handle:
            handle.write(splice(text, mapping_block(self._sizes)))
        logger.info("mapped %d products in %s", len(self._sizes), JUNGLE_NAME)
        return self

    def mapping(self) -> Dict[str, int]:
        """Reads the committed mapping back out of the jungle."""
        jungle = self._path(JUNGLE_NAME)
        if not os.path.exists(jungle):
            return {}
        with open(jungle, "r", encoding="utf-8") as handle:
            text = handle.read()
        block = BLOCK_PATTERN.search(text)
        if block is None:
            return {}
        return {
            match.group(1): int(match.group(2))
            for match in MAPPING_PATTERN.finditer(block.group(0))
        }

    def unmapped_directories(self, sizes) -> List[str]:
        """Icon directories present in the project that no product asks for."""
        if not os.path.isdir(self._project_directory):
            return []
        found = (
            (name, ICON_DIRECTORY_PATTERN.match(name))
            for name in os.listdir(self._project_directory)
        )
        return sorted(
            name for name, match in found if match and int(match.group(1)) not in sizes
        )

    # -------------------------------------------------------------------- output

    def table(self) -> str:
        """The product to icon size table, as markdown, for a project README."""
        return table(self.mapping() or self._sizes)

    def check(self) -> List[Tuple[bool, str]]:
        """
        Verifies the committed icons and mapping, as a list of (passed, message).

        Needs no SDK: the mapping in the jungle is itself the device to size table,
        and is cross-checked against the SDK only when the definitions are present.
        """
        report: List[Tuple[bool, str]] = []
        mapped = self.mapping()
        products = set(self.products())

        missing = sorted(products - set(mapped))
        extra = sorted(set(mapped) - products)
        report.append(
            (
                not missing,
                f"every manifest product has an icon resourcePath ({len(products)})"
                if not missing
                else f"no icon resourcePath for {missing}",
            )
        )
        report.append(
            (
                not extra,
                "no resourcePath for a product outside the manifest"
                if not extra
                else f"resourcePath for unknown products {extra}",
            )
        )

        for size in sorted(set(mapped.values()), reverse=True):
            icon = os.path.join(self._icon_directory(size), LAUNCHER_ICON_NAME)
            if not os.path.exists(icon):
                report.append((False, f"{icon} is missing"))
                continue
            actual = read_png_size(icon)
            report.append(
                (
                    actual == (size, size),
                    f"{icon} is {size}x{size}"
                    if actual == (size, size)
                    else f"{icon} is {actual}, its directory promises {size}x{size}",
                )
            )
            declaration = os.path.join(self._icon_directory(size), "drawables.xml")
            declared = os.path.exists(declaration)
            if declared:
                with open(declaration, "r", encoding="utf-8") as handle:
                    declared = "LauncherIcon" in handle.read()
            report.append((declared, f"{declaration} declares LauncherIcon"))

        orphans = self.unmapped_directories(set(mapped.values()))
        report.append(
            (
                not orphans,
                "no icon directory left unmapped"
                if not orphans
                else f"icon directories no product asks for: {orphans}",
            )
        )

        report.extend(self._check_against_sdk(mapped))
        return report

    def _check_against_sdk(self, mapped: Dict[str, int]) -> List[Tuple[bool, str]]:
        try:
            self.resolve_sizes()
        except LauncherIconError as error:
            logger.info("not cross-checked against the SDK: %s", error)
            return []
        wrong = sorted(
            (product, mapped[product], size)
            for product, size in self._sizes.items()
            if product in mapped and mapped[product] != size
        )
        return [
            (
                not wrong,
                f"every mapping matches the device's launcherIcon ({len(self._sizes)})"
                if not wrong
                else f"mappings disagreeing with the SDK: {wrong[:3]}",
            )
        ]


# ------------------------------------------------------------------- free helpers


def mapping_block(sizes: Dict[str, int]) -> str:
    """Renders the generated jungle block for a product to size mapping."""
    lines = [
        BEGIN_MARKER,
        "# Launcher icon size is per device, not per device family.",
        "# Regenerate with: garmin-graphics-generator icons",
    ]
    for product in sorted(sizes):
        directory = ICON_DIRECTORY_TEMPLATE.format(size=sizes[product])
        lines.append(f"{product}.resourcePath = $({product}.resourcePath);{directory}")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def splice(text: str, block: str) -> str:
    """
    Replaces the generated block in a jungle file, or appends it if absent.

    Every existing block goes, not just the first: a project generated by an earlier
    tool carries a marker naming that tool, and leaving it in place would map each
    product twice.
    """
    first = BLOCK_PATTERN.search(text)
    if first is None:
        return text.rstrip("\n") + "\n\n" + block
    return text[: first.start()] + block + BLOCK_PATTERN.sub("", text[first.end() :])


def table(sizes: Dict[str, int]) -> str:
    """
    Renders the product to icon size table as markdown.

    Sorted by size rather than by product, because the point the table has to make
    is that the sizes cut across every other way of grouping the devices.
    """
    rows = [
        (product, f"{sizes[product]} x {sizes[product]}")
        for product in sorted(sizes, key=lambda p: (-sizes[p], p))
    ]
    left = max([len("Product")] + [len(row[0]) for row in rows])
    right = max([len("Icon")] + [len(row[1]) for row in rows])
    lines = [
        f'| {"Product":<{left}} | {"Icon":>{right}} |',
        f'| :{"-" * (left - 1)} | {"-" * (right - 1)}: |',
    ]
    lines += [f"| {product:<{left}} | {size:>{right}} |" for product, size in rows]
    return "\n".join(lines) + "\n"


__all__ = [
    "LauncherIconError",
    "LauncherIconGenerator",
    "load_renderer",
    "mapping_block",
    "read_png_size",
    "resample_renderer",
    "splice",
    "table",
]
